# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [3]:
import numpy as np
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49

In [4]:
y = np.arange(10,50)
print(y)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Find the shape of previous array in question 3

In [5]:
print(y.shape)

(40,)


5. Print the type of the previous array in question 3

In [ ]:
print(y.dtype)

6. Print the numpy version and the configuration


In [6]:
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Alima/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Alima/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Alima/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Alima/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Alima/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Alima/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Alima/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Alima/anaconda3\\Library\\include']
None


7. Print the dimension of the array in question 3


In [7]:
print(y.ndim)

1


8. Create a boolean array with all the True values

In [8]:
z = np.ones((2,2), dtype = bool)
print(z)

[[ True  True]
 [ True  True]]


9. Create a two dimensional array




In [29]:
arry_2D = np. array([(2,3,4),(5,6,7)])
print(arry_2D)
print(arry_2D.ndim)
arr2d = np.arange(15).reshape(3,5)
print(arr2d)
print(arr2d.ndim)

[[2 3 4]
 [5 6 7]]
2
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
2


10. Create a three dimensional array



In [27]:
arry_3D = np. array([[(2,3,4),(5,6,7)],[(8,9,10),(11,12,13)]]) 
print(arry_3D)
print(arry_3D.ndim)
arr3d = np.arange(30).reshape((3,5,2))
print(arr3d)
print(arr3d.ndim)

[[[ 2  3  4]
  [ 5  6  7]]

 [[ 8  9 10]
  [11 12 13]]]
3
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]]]
3


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [20]:
reverse_vector = np.arange(11)
print(reverse_vector)
rev = reverse_vector[::-1]
print(rev)

[ 0  1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1  0]


12. Create a null vector of size 10 but the fifth value which is 1 

In [35]:
null = np.zeros(10)
null[5]=1
print(null)
print("size = ",null.size)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
size =  10


13. Create a 3x3 identity matrix

In [37]:
identity = np.identity(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [40]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr.astype(float))

[1 2 3 4 5]
[1. 2. 3. 4. 5.]


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [41]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
new_arr = np.multiply(arr1,arr2)
print(new_arr)


[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [42]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
compression = (arr1==arr2)
print(compression)

[[False False False]
 [False False False]]


17. Extract all odd numbers from arr with values(0-9)

In [14]:
import numpy as np
array = np.arange(10)    
odd = []    
for i in array:
 if i % 2 != 0:
   odd.append(i)
print(np.array(odd)) 

[1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [27]:
arr = np.arange(10)
print(arr)
arr[arr%2!= 0]=-1
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [43]:
arr = np.arange(10)
print(arr)
arr[5:9] = 12
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [41]:
import numpy as np
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [48]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[1,1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [69]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0,0,::]=64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [75]:
arr1 =  np.arange(10).reshape(2,5)
print(arr1)
new_arr = arr1[0]
new_arr

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [79]:
arr1 =  np.arange(10).reshape(2,5)
print(arr1)
arr1[1,2]


[[0 1 2 3 4]
 [5 6 7 8 9]]


7

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [81]:
arr1 =  np.arange(10).reshape(2,5)
print(arr1)

[[0 1 2 3 4]
 [5 6 7 8 9]]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [82]:
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.38219216 0.70367328 0.6727383  0.65362565 0.84267353 0.273679
  0.15885747 0.89907305 0.37592178 0.36493876]
 [0.54775679 0.75157523 0.67131712 0.41664877 0.63978225 0.39210536
  0.33789525 0.70295283 0.27492437 0.59307034]
 [0.29793977 0.33105055 0.75716087 0.84497038 0.9823279  0.74363278
  0.28274521 0.77988645 0.19788309 0.28606015]
 [0.4665453  0.28168027 0.65516877 0.62066664 0.47618977 0.06314991
  0.61522329 0.46457245 0.97167311 0.55002238]
 [0.80931825 0.50445744 0.68302123 0.13584685 0.6333437  0.36974012
  0.34743184 0.74987452 0.9560788  0.32747949]
 [0.99793156 0.68616811 0.08633545 0.10391544 0.96983632 0.41887223
  0.67256463 0.7228222  0.10815625 0.15070516]
 [0.05593448 0.93211755 0.6254514  0.29899309 0.26284549 0.33868687
  0.40307934 0.31721409 0.06783785 0.20068183]
 [0.76324855 0.91431919 0.27603626 0.91305009 0.39124826 0.81116623
  0.53078368 0.42643261 0.91130387 0.9372242 ]
 [0.60631656 0.43910076 0.45993741 0.10593711 0.47554649 0.1387567

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [83]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

print(np.intersect1d(a, b))

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [84]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print([key for key, val in enumerate(a) if val in set(b)])

[1, 3, 5, 7]


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [92]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data
names != 'Will' 
data[~(names == 'Will')]


array([[ 0.18545094, -0.03788961, -1.74151545,  1.2118189 ],
       [-0.19778771, -0.09975127, -0.0859552 ,  0.89734267],
       [-0.64411079,  0.4580599 ,  1.4543449 ,  1.91547533],
       [-1.63907638,  0.80868096,  0.3307688 ,  0.63680325],
       [ 0.91410746, -0.2523957 ,  0.24715044, -0.31061182]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [97]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
m = (names != 'Joe') | (names != 'Will')
data[~(names == 'Joe') | ~(names == 'Will')]

array([[-2.37610726, -0.34568987, -2.380425  , -0.37596347],
       [ 1.09227116,  1.6154908 ,  0.46058919, -0.63628343],
       [ 1.95625976, -0.70300337, -0.28402844, -0.93181502],
       [-0.09753056, -0.27521225, -2.26647756, -0.80640032],
       [-1.26414244, -0.72830253, -0.22170954, -1.04199745],
       [-1.68269017, -0.96277017,  0.35541515, -0.93098757],
       [-0.16250878, -0.65041071,  0.52723941,  0.5807892 ]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [104]:
arr2d = np.arange(0,15).reshape(5,3)
arr2d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [109]:
arr = np.arange(0,16).reshape(2,2,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

33. Swap axes of the array you created in Question 32

In [112]:
arr1 =arr.reshape(2,2,4).swapaxes(0,2)
arr1

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [138]:
array = np.arange(10)
root = np.sqrt (array)
print(root)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [151]:
array1 = np.array([2,9,5,11,1])
array2= np.array([3,8,9,1,10])
c = np.maximum(array1, array2)
print(c)

[ 3  9  9 11 10]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [130]:
names = np.unique(names)
names = sorted(set(names))
print(names)

['Bob', 'Joe', 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [126]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
c = np.setdiff1d(b,a)
print(c)

[6 7 8 9]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [118]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray = np.delete(sampleArray , 1, axis = 1)
sampleArray = np.insert(sampleArray , 1, newColumn, axis = 1) 
print (sampleArray)

[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [116]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
z = np.dot(x,y)
print(z)

[[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [133]:
arr = np.random.normal(size= (20))
print(arr)
comulative_sum = np.cumsum(arr)
print(comulative_sum)

[ 1.41711176 -0.24592156 -0.45439331  0.46387636 -0.4950318  -0.62911794
 -0.4721045  -0.61289856 -1.39570273 -0.59376666 -2.00799094 -1.0876901
 -0.11962384  0.51455638 -1.32903195 -2.44031111  0.23440931  0.57454182
  1.20051451 -1.77072723]
[ 1.41711176  1.1711902   0.71679689  1.18067325  0.68564145  0.0565235
 -0.41558099 -1.02847955 -2.42418228 -3.01794894 -5.02593988 -6.11362998
 -6.23325381 -5.71869744 -7.04772939 -9.4880405  -9.25363118 -8.67908936
 -7.47857485 -9.24930208]
